# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 05:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quote',
            managers=[
                ('QuoteManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
