# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_remove_quote_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quotes',
            field=models.CharField(max_length=255),
        ),
    ]
